### ISSUE TITLE
error: no module named 'transformers'

### ISSUE THREAD

**Issue by shoumo2021** [Rostlab/EAT#6]
Following installation as described, eat.py is no longer working - with error message:
shoumo@Shoumos-MacBook-Pro-2 EAT % python eat.py --lookup data/example_data_subcell/deeploc_lookup.fasta --queries data/example_data_subcell/la_query_setHARD.fasta --output eat_results/

Traceback (most recent call last):
  File "/Users/shoumo/EAT/eat.py", line 515, in <module>
    main()
  File "/Users/shoumo/EAT/eat.py", line 496, in main
    eater = EAT(lookup_p, query_p, output_d,
  File "/Users/shoumo/EAT/eat.py", line 216, in __init__
    self.lookup_ids, self.lookup_embs = self.read_inputs(lookup_p)
  File "/Users/shoumo/EAT/eat.py", line 262, in read_inputs
    self.Embedder = Embedder()
  File "/Users/shoumo/EAT/eat.py", line 129, in __init__
    self.embedder, self.tokenizer = self.get_prott5()
  File "/Users/shoumo/EAT/eat.py", line 135, in get_prott5
    from transformers import T5EncoderModel, T5Tokenizer
ModuleNotFoundError: No module named 'transformers'

**Comment by mheinzinger** [comment]
Yeah, sorry I've messed up the requirements with one of my last edits.
I've re-added the transformers library.
